name: Rust

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: cargo build --release --verbose
      
    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v2
      with:
        name: RWM
        path: ${{github.workspace}}/target/release/
        
  release:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'

    steps:
    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}_${{ github.sha }}
        release_name: Release ${{ github.ref }}
        draft: true
        prerelease: false

    - name: Store Release url
      run: |
        echo "${{ steps.create_release.outputs.upload_url }}" > ./upload_url
    - uses: actions/upload-artifact@v1
      with:
        path: ./upload_url
        name: upload_url

  publish:
    runs-on: ubuntu-latest
    needs: release
    if: github.event_name == 'push'

    steps:
    - name: Download build artifacts
      id: download_build_artifacts
      uses: actions/download-artifact@v2
      with:
        name: RWM
        path: ./artifacts/RWM

    - name: Download URL
      uses: actions/download-artifact@v1
      with:
        name: upload_url
        path: ./artifacts/

    - id: set_upload_url
      run: |
        upload_url=`cat ./artifacts/upload_url`
        echo ::set-output name=upload_url::$upload_url
        
    - name: Zip artifacts
      run: |
        cd artifacts/RWM
        zip -r RWM.zip *
        mv RWM.zip ../../

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: RWM.zip
        asset_name: RWM.zip
        asset_content_type: application/zip

    - name: Upload Release exe Asset
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.set_upload_url.outputs.upload_url }}
        asset_path: artifacts/RWM/rwm.exe
        asset_name: RWM.exe
        asset_content_type: application/exe
